//! Offline comparison harness: generates a deterministic, reproducible set
//! of 20 non-terminal Connect Four positions spanning plies 4-20 and prints,
//! for each, the position's own score (from the mover's perspective) and
//! the seven per-column child scores exactly as connect4.gamesolver.org
//! overlays them -- so the orchestrator can paste each printed `URL` into a
//! browser and diff the numbers by eye.
//!
//! Wired as a `[[bin]]` target of the `connect4_engine` package (see
//! `engine/Cargo.toml`), source kept at `tools/compare_gamesolver.rs` per
//! the repo layout -- the same pattern `tools/gen_book.rs` already uses.
//! This binary makes no network calls: it is entirely offline,
//! deterministic, and prints its own reference numbers only. Any actual
//! cross-checking against gamesolver.org happens outside this process.
//!
//! ## Scoring convention
//!
//! Both the position score and the per-column scores follow exactly the
//! convention `docs/ENGINE.md` and `engine/src/analysis.rs` already use --
//! no transformation is applied here. `engine/tests/reference.rs`'s
//! fixtures are Pascal Pons's own published test sets, and gamesolver.org
//! is Pons's own site, so the conventions already agree:
//!
//! - Position score: from the perspective of the player to move in the
//!   analysed position (`Solver::solve`).
//! - Column score: the score of the position AFTER playing that column,
//!   from the perspective of the player who was to move BEFORE playing it
//!   -- i.e. the negation of the child position's own score. This binary
//!   reuses `connect4_engine::analysis::analyse` directly (rather than
//!   reimplementing the per-column rule) so there is exactly one
//!   implementation of that rule in the whole codebase.
//!
//! ## Position generation
//!
//! Position #1 is always the known "7375" trap position (ply 4, Wave 8's
//! `TRAP_ROOT` in `engine/src/tactical.rs`) -- a good discriminative check
//! since its double-threat structure is easy to get subtly wrong.
//! Positions #2-20 are generated by random legal playouts from the empty
//! board using a hand-rolled, dependency-free PRNG (`SplitMix64`, the same
//! generator `tools/gen_book.rs` already uses for its own seeded
//! verification sample) seeded deterministically (`SEED` below) so
//! re-running this binary always prints the identical 20 positions.
//!
//! A playout that reaches a terminal position (a completed four-in-a-row,
//! or a full board) at or before its target ply is discarded in full and
//! retried from the empty board, continuing to draw from the same RNG
//! stream -- so the exact sequence of retries is itself deterministic. Win
//! detection is reimplemented independently of the engine's own
//! (crate-private) internals via `TerminalTracker`, following the
//! identical pattern `tools/gen_book.rs`'s own `TerminalTracker` uses and
//! for the same reason (see that file's module doc comment):
//! `Position::current`/`mask` are `pub(crate)`, not visible to this
//! separate binary crate.
//!
//! `PLY_SCHEDULE` fixes the 20 target plies up front: position #1 is ply 4
//! (the fixed trap root), and the remaining 19 cover plies 4 through 20 at
//! least once each, with a few plies repeated (using a fresh, independent
//! playout each time) so every one of the six required bands (4-6, 7-9,
//! 10-12, 13-15, 16-18, 19-20) gets at least two positions.

use connect4_engine::analysis::{self, ColumnEval};
use connect4_engine::position::{Position, HEIGHT, WIDTH};
use connect4_engine::solver::Solver;

/// Total playable cells on the board (7 * 6 = 42): a full board.
const TOTAL_CELLS: u32 = WIDTH * HEIGHT;

/// Deterministic seed for the whole run. Re-running this binary with the
/// same seed always reproduces the identical 20 positions (except #1,
/// which is fixed regardless of the seed) and therefore the identical
/// scores.
const SEED: u64 = 0x4655_5749_5345;

/// The known ply-4 trap position from Wave 8 (`tactical::TRAP_ROOT` in
/// `engine/src/tactical.rs`), reproduced here as a plain literal rather
/// than imported -- `tactical` doesn't expose it as a public constant, and
/// this binary otherwise has no reason to depend on that module at all.
const TRAP_ROOT: &str = "7375";

/// Target ply for each of the 20 positions, in order. Position 0 is the
/// fixed trap root (ply 4); the rest are generated. Covers every ply
/// 4..=20 at least once, with a few repeated (each an independently drawn
/// playout) so every required band -- 4-6, 7-9, 10-12, 13-15, 16-18, 19-20
/// -- ends up with at least two positions. See the module doc comment.
const PLY_SCHEDULE: [u32; 20] = [
    4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 6, 9, 13,
];

fn main() {
    let mut rng = SplitMix64::new(SEED);

    for (i, &target_ply) in PLY_SCHEDULE.iter().enumerate() {
        let (pos, moves) = if i == 0 {
            let pos = Position::from_moves(TRAP_ROOT)
                .expect("TRAP_ROOT is a known-valid move sequence");
            assert_eq!(pos.moves(), target_ply, "TRAP_ROOT must be ply 4");
            (pos, TRAP_ROOT.to_string())
        } else {
            random_non_terminal_position(target_ply, &mut rng)
        };

        // Fresh solver per position, 64 MB TT (`Solver::new`'s default
        // budget, per `docs/ENGINE.md`) -- reused for both the position
        // score and the per-column analysis below, exactly as the
        // delegation prompt specifies.
        let mut solver = Solver::new();
        let score = solver.solve(&pos);
        let result = analysis::analyse(&mut solver, &pos, u32::MAX);

        let cols: Vec<String> = result
            .columns
            .iter()
            .map(|c| match c {
                ColumnEval::Score { score } => score.to_string(),
                ColumnEval::Full => "X".to_string(),
                ColumnEval::Unknown => panic!(
                    "column came back Unknown under a u32::MAX node budget \
                     (position {moves:?}) -- this should be unreachable"
                ),
            })
            .collect();

        println!(
            "POS {:02} ply={} moves={} score={} cols={}",
            i + 1,
            pos.moves(),
            moves,
            score,
            cols.join(",")
        );
        println!("URL https://connect4.gamesolver.org/?pos={moves}");
    }
}

/// Generate a random legal playout of exactly `target_ply` moves from the
/// empty board, retrying from scratch (continuing to draw from the same
/// RNG stream) any attempt that hits a terminal position (a win, or a full
/// board) at or before `target_ply`. Returns the resulting non-terminal
/// `Position` and the 1-indexed move-string that reaches it.
fn random_non_terminal_position(target_ply: u32, rng: &mut SplitMix64) -> (Position, String) {
    loop {
        let mut pos = Position::new();
        let mut tracker = TerminalTracker::new();
        let mut moves = String::with_capacity(target_ply as usize);
        let mut terminal = false;

        for _ in 0..target_ply {
            let legal: Vec<u32> = (0..WIDTH).filter(|&c| pos.can_play(c)).collect();
            if legal.is_empty() {
                terminal = true;
                break;
            }
            let idx = (rng.next_u64() as usize) % legal.len();
            let col = legal[idx];

            if tracker.is_winning_move(col as usize) {
                terminal = true;
                break;
            }

            pos.play(col);
            tracker.play(col as usize);
            moves.push(char::from_digit(col + 1, 10).expect("col + 1 is 1..=7"));

            if pos.moves() == TOTAL_CELLS {
                terminal = true;
                break;
            }
        }

        if !terminal && pos.moves() == target_ply {
            return (pos, moves);
        }
        // Discard this whole attempt and retry, continuing to draw from
        // the same `rng` -- deterministic given the fixed seed.
    }
}

// ---------------------------------------------------------------------
// Independent terminal detection -- deliberately reimplemented rather than
// reusing the engine's own (crate-private) win detection. Structurally
// identical to `tools/gen_book.rs`'s own `TerminalTracker`, for the same
// reason: `Position::current`/`mask` are `pub(crate)`, invisible to this
// separate binary crate.
// ---------------------------------------------------------------------

/// Tracks board state in parallel with a `Position` purely to answer "does
/// playing `col` right now complete a four-in-a-row for the player to
/// move" and nothing else.
#[derive(Clone, Copy)]
struct TerminalTracker {
    cells: [[Option<bool>; HEIGHT as usize]; WIDTH as usize],
    heights: [usize; WIDTH as usize],
    first_to_move: bool,
}

impl TerminalTracker {
    fn new() -> TerminalTracker {
        TerminalTracker {
            cells: [[None; HEIGHT as usize]; WIDTH as usize],
            heights: [0; WIDTH as usize],
            first_to_move: true,
        }
    }

    /// Would dropping a disc into `col` right now complete a four-in-a-row
    /// for the player about to move? Caller is responsible for having
    /// already checked the column has room.
    fn is_winning_move(&self, col: usize) -> bool {
        let row = self.heights[col];
        let player = self.first_to_move;
        const DIRECTIONS: [(isize, isize); 4] = [(1, 0), (0, 1), (1, 1), (1, -1)];
        for (dc, dr) in DIRECTIONS {
            let mut run = 1u32; // the hypothetical disc itself
            for sign in [1isize, -1isize] {
                let mut cc = col as isize + dc * sign;
                let mut rr = row as isize + dr * sign;
                while (0..WIDTH as isize).contains(&cc)
                    && (0..HEIGHT as isize).contains(&rr)
                    && self.cells[cc as usize][rr as usize] == Some(player)
                {
                    run += 1;
                    cc += dc * sign;
                    rr += dr * sign;
                }
            }
            if run >= 4 {
                return true;
            }
        }
        false
    }

    fn play(&mut self, col: usize) {
        let row = self.heights[col];
        self.cells[col][row] = Some(self.first_to_move);
        self.heights[col] += 1;
        self.first_to_move = !self.first_to_move;
    }
}

// ---------------------------------------------------------------------
// Hand-rolled PRNG: SplitMix64, no external dependency -- the same
// generator `tools/gen_book.rs` already uses for its own seeded sampling,
// kept as its own independent copy here rather than shared (this file
// compiles as a wholly separate bin crate).
// ---------------------------------------------------------------------

struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(seed: u64) -> SplitMix64 {
        SplitMix64 { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
}
